### ISSUE TITLE
Failed to activate the localeapp package

### ISSUE THREAD

**Issue by ticolucci** [mgbatchelor/atom-localeapp#1]
Steps to reproduce:
1) Update atom to latest

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [localeapp](https://github.com/mgbatchelor/atom-localeapp) package, v0.1.3
### Stack Trace

Failed to activate the localeapp package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/ticolucci/.atom/packages/localeapp/lib/localeapp.js:6:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-slim, v0.4.0
linter-slim, v0.5.1
localeapp, v0.1.3
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by kieranklaassen** [comment]
+1
